export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_LOADING = "TRANSACTION_LOADIGN";
export const TRANSACTION_FAIL = "TRANSACTION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
