export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_FAIL = "PROFILE_FAIL";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PICTURE_SUCCESS = "UPDATE_PICTURE_SUCCESS";
export const UPDATE_PICTURE_LOADING = "UPDATE_PICTURE_LOADING";
export const UPDATE_PICTURE_FAIL = "UPDATE_PICTURE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
